# Generated by Django 4.2.6 on 2024-02-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0002_alter_userprofile_vet_professional"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="vet_professional",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
