# Generated by Django 4.2.6 on 2024-02-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_userprofile_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
