# Generated by Django 4.2.6 on 2024-03-26 23:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0004_contact_delete_follow"),
        ("Users", "0004_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="Social.Contact",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
