# Generated by Django 4.2.6 on 2024-04-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0007_remove_veterinaryprofessional_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinaryprofessional",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
