# Generated by Django 4.2.6 on 2024-04-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0008_veterinaryprofessional_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinaryprofessional",
            name="field_of_work",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veterinaryprofessional",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="veterinaryprofessional",
            name="registration_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
