# Generated by Django 4.2.6 on 2024-04-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0009_veterinaryprofessional_field_of_work_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veterinaryprofessional",
            name="verification_code_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
