# Generated by Django 4.2.6 on 2024-03-27 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Social", "0005_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "author")},
        ),
    ]
