# Generated by Django 4.2.6 on 2024-03-27 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Social", "0006_rename_user_like_author_alter_like_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="verify",
            old_name="user",
            new_name="author",
        ),
        migrations.AlterUniqueTogether(
            name="verify",
            unique_together={("post", "author")},
        ),
    ]
