# Generated by Django 4.2.6 on 2024-04-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0009_offer_saveditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="media",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to=""
            ),
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, default="default.png", null=True, upload_to=""
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Social.item",
                    ),
                ),
            ],
        ),
    ]
