# Generated by Django 4.2.6 on 2024-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0011_item_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=20, null=True
            ),
        ),
    ]
