# Generated by Django 4.2.6 on 2024-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0012_item_latitude_item_location_item_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="condition",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("ULN", "Used - Like New"),
                    ("UG", "Used - Good"),
                ],
                default="ULN",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=12, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=12, max_digits=15, null=True
            ),
        ),
    ]
