# Generated by Django 4.2.6 on 2024-04-11 20:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Social", "0013_alter_item_condition_alter_item_latitude_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SavedItem",
            new_name="SaveItem",
        ),
    ]
