# Generated by Django 4.2.6 on 2024-04-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Social", "0014_rename_saveditem_saveitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=30, null=True
            ),
        ),
    ]
